### ISSUE TITLE
Suggestions of changes regarding French ressources

### ISSUE THREAD

**Issue by dbitouze** [bdtc/docsurvey#12]
(I wanted to provide a PR in order to make easier for you changes regarding French ressources but this repository doesn't contain the code of `docsurvey` :thinking:)

Anyway, here are the changes that I suggest regarding French ressources:

- TEX pour l’Impatient → TeX pour l’Impatient
- https://ctan.org/pkg/faq-fr → https://faq.gutenberg-asso.fr/
- Tout Ce Que Vous Avez Toujours Voulu Savoir Sur LaTeX Sans Jamais Oser Le Demander → Tout ce que vous avez toujours voulu savoir sur LaTeX sans jamais oser le demander
- XeLaTeX— Appliqué Aux Sciences Humaines → XeLaTeX — Appliqué aux sciences humaines
- https://www.learnlatex.org/ → https://www.learnlatex.org/fr/

**Comment by bdtc** [comment]
Done for version 2024/03/18.
